name: Env Demo

on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  env_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Connet to Env
        run: echo "The application environment is $APP_ENV"