name: Inputs Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: dev
        options:
          - dev
          - staging
          - production
      artifact_tag:
        description: Tag for the deployment
        required: true
jobs:
  inputs_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Deploying the ${{ inputs.artifact_tag}} application to ${{ inputs.environment}}"
